<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>
	todo:
		order tags
	</string>
	<key>fileTypes</key>
	<array>
		<string>il</string>
		<string>ile</string>
		<string>tf</string>
		<string>cdf</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\(</string>
	<key>foldingStopMarker</key>
	<string>\)</string>
	<key>name</key>
	<string>SKILL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.skill</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(;).*$\n?</string>
			<key>name</key>
			<string>comment.line.semicolon.skill</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.skill</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.skill</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)(L|l|UL|ul|u|U|F|f|ll|LL|ull|ULL)?\b</string>
			<key>name</key>
			<string>constant.numeric.skill</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((\w+)(?=\s*=))\b</string>
			<key>name</key>
			<string>constant.language.skill</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:t|nil)\b</string>
			<key>name</key>
			<string>constant.language.boolean.skill</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:case|cond|else|for|foreach|if|let|prog|then|unless|when|while)\b</string>
			<key>name</key>
			<string>keyword.control.skill</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&lt;|&lt;=|&gt;|&gt;=|==|!=|&amp;&amp;|\|\|</string>
			<key>name</key>
			<string>keyword.operator.logical.skill</string>
		</dict>
		<dict>
			<key>match</key>
			<string>~&gt;|-&gt;</string>
			<key>name</key>
			<string>keyword.other.skill</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b(?i:(defun|defmethod|defmacro|procedure))\b)()</string>
			<key>name</key>
			<string>keyword.other.special-method.skill</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.skill</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.skill</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.skill</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.skill</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.skill</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b((\w+)(?=\())\b</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.skill</string>
	<key>uuid</key>
	<string>b3933160-034f-4575-a340-73ecb5f90962</string>
</dict>
</plist>
